### ISSUE TITLE
Getting error on console besides everything is ok on the config

### ISSUE THREAD

**Issue by ayuwooh** [CoachLuck/BackPacksPlus#19]
Getting this error on console, but my config is fine and the br.yml file exists, don't know why I'm getting this error

![vivaldi_rj9ysdqtXm](https://user-images.githubusercontent.com/81534459/114436824-30bf9f00-9b9c-11eb-988f-34b64739b0f8.jpg)

**Comment by aj-rom** [comment]
@ayukays If you are attempting to use the Portuguese translations they would be under the file `pt-br.yml`. Thus in your `config.yml` language would be set to `pt-br` instead of `br`

Check out the lang folder for all acceptable file names.

[ Here is the directory](https://github.com/aj-rom/BackPacksPlus/tree/master/src/main/resources/lang).
